steps:
# 1) 安装依赖
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# 2) （可选）如果有前端构建步骤
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['run', 'build']

# 3) 用 Dockerfile 构建镜像，并推到 Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/chatapp'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/chatapp'

# 4) 部署到 Cloud Run（无服务器容器服务）
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy chatapp \
      --image gcr.io/$PROJECT_ID/chatapp \
      --region us-central1 \
      --platform managed \
      --allow-unauthenticated \
      --set-env-vars MONGO_URI="mongodb+srv://chatroom:ClKSCRF0Iq6uxI1a@cluster0.x8ivpkx.mongodb.net/chatapp?retryWrites=true&w=majority"

images:
- 'gcr.io/$PROJECT_ID/chatapp'